name: pdfium_bindings
description: This project aims to wrap the complete [Pdfium](https://pdfium.googlesource.com/pdfium/) API in dart, over FFI.
version: 2.0.1
homepage: https://github.com/insinfo/pdfium_bindings

environment:
  sdk: '>=3.0.0'

dependencies:
  ffi: ^2.0.2
  ffigen: ^8.0.2
  image: ^4.0.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.2
  http: any
  lint: ^2.0.0
#dart run ffigen --config ffigen.yaml